CREATE VIEW AVAILABLE_BOOK
AS
	SELECT C.ID_BOOK AS "ID book",C.ISBN, C.TITLE AS "Book",
			C.NUMBER_AVAILABLE AS "Available number", C.NAME_TYPE AS "Type"
	FROM  BOOK AS C
	WHERE C.NUMBER_AVAILABLE>0

GO

CREATE VIEW MEMBERS
AS
	SELECT M.FIRST_NAME AS "First name", M.LAST_NAME AS "Last name",
			M.DATE_OF_MEMBERSHIP AS "Membership date",
			M.DATE_OF_PAYMENT as "Renewal date", M.TYPE_MEMBER AS "Type", C.CITY_NAME AS "City"
	FROM LIB_MEMBER AS M, CITY AS C
	WHERE M.PBR=C.PBR
