from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QDate


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(924, 650)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(624, 350))
        MainWindow.setMaximumSize(QtCore.QSize(924, 650))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setGeometry(QtCore.QRect(9, 39, 541, 541))
        self.tableView.setObjectName("tableView")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(560, 39, 331, 541))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.scrollArea.setFont(font)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, -390, 313, 1069))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_3.setVerticalSpacing(25)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_IDBookDelete = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_IDBookDelete.setObjectName("lineEdit_IDBookDelete")
        self.gridLayout_3.addWidget(self.lineEdit_IDBookDelete, 30, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 21, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 24, 1, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 19, 1, 1, 3)
        self.pushButton_showMembers = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_showMembers.setObjectName("pushButton_showMembers")
        self.gridLayout_3.addWidget(self.pushButton_showMembers, 3, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 25, 1, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 28, 1, 1, 3)
        self.label_14 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 17, 1, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 15, 1, 1, 2)
        self.lineEdit_IDAuthorsBooks = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_IDAuthorsBooks.sizePolicy().hasHeightForWidth())
        self.lineEdit_IDAuthorsBooks.setSizePolicy(sizePolicy)
        self.lineEdit_IDAuthorsBooks.setMaximumSize(QtCore.QSize(100, 100))
        self.lineEdit_IDAuthorsBooks.setObjectName("lineEdit_IDAuthorsBooks")
        self.gridLayout_3.addWidget(self.lineEdit_IDAuthorsBooks, 6, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.line.setFont(font)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 14, 1, 1, 3)
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 30, 1, 1, 1)
        self.lineEdit_IDMembRenewal = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_IDMembRenewal.sizePolicy().hasHeightForWidth())
        self.lineEdit_IDMembRenewal.setSizePolicy(sizePolicy)
        self.lineEdit_IDMembRenewal.setMaximumSize(QtCore.QSize(100, 100))
        self.lineEdit_IDMembRenewal.setObjectName("lineEdit_IDMembRenewal")
        self.gridLayout_3.addWidget(self.lineEdit_IDMembRenewal, 21, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(False)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 23, 1, 1, 3)
        self.lineEdit_nameAuth = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_nameAuth.setObjectName("lineEdit_nameAuth")
        self.gridLayout_3.addWidget(self.lineEdit_nameAuth, 17, 3, 1, 1)
        self.radioButton_r2 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_r2.sizePolicy().hasHeightForWidth())
        self.radioButton_r2.setSizePolicy(sizePolicy)
        self.radioButton_r2.setObjectName("radioButton_r2")
        self.gridLayout_3.addWidget(self.radioButton_r2, 4, 2, 1, 1)
        self.lineEdit_IDLoanMemb = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_IDLoanMemb.sizePolicy().hasHeightForWidth())
        self.lineEdit_IDLoanMemb.setSizePolicy(sizePolicy)
        self.lineEdit_IDLoanMemb.setMaximumSize(QtCore.QSize(100, 100))
        self.lineEdit_IDLoanMemb.setObjectName("lineEdit_IDLoanMemb")
        self.gridLayout_3.addWidget(self.lineEdit_IDLoanMemb, 1, 2, 1, 1)
        self.pushButton_return = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_return.sizePolicy().hasHeightForWidth())
        self.pushButton_return.setSizePolicy(sizePolicy)
        self.pushButton_return.setObjectName("pushButton_return")
        self.gridLayout_3.addWidget(self.pushButton_return, 26, 1, 1, 3)
        self.pushButton_renewal = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_renewal.setObjectName("pushButton_renewal")
        self.gridLayout_3.addWidget(self.pushButton_renewal, 21, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 29, 1, 1, 1)
        self.lineEdit_titleBook = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_titleBook.setObjectName("lineEdit_titleBook")
        self.gridLayout_3.addWidget(self.lineEdit_titleBook, 16, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 6, 1, 1, 1)
        self.lineEdit_nameMemb = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_nameMemb.setObjectName("lineEdit_nameMemb")
        self.gridLayout_3.addWidget(self.lineEdit_nameMemb, 15, 3, 1, 1)
        self.pushButton_showAllMembers = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_showAllMembers.sizePolicy().hasHeightForWidth())
        self.pushButton_showAllMembers.setSizePolicy(sizePolicy)
        self.pushButton_showAllMembers.setObjectName("pushButton_showAllMembers")
        self.gridLayout_3.addWidget(self.pushButton_showAllMembers, 13, 1, 1, 3)
        self.pushButton_deleteBook = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_deleteBook.setObjectName("pushButton_deleteBook")
        self.gridLayout_3.addWidget(self.pushButton_deleteBook, 30, 3, 1, 1)
        self.lineEdit_IDMembDelete = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_IDMembDelete.setObjectName("lineEdit_IDMembDelete")
        self.gridLayout_3.addWidget(self.lineEdit_IDMembDelete, 29, 2, 1, 1)
        self.line_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setMinimumSize(QtCore.QSize(0, 0))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout_3.addWidget(self.line_4, 27, 1, 1, 3)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 1, 1, 1)
        self.pushButton_authorsBooks = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_authorsBooks.setObjectName("pushButton_authorsBooks")
        self.gridLayout_3.addWidget(self.pushButton_authorsBooks, 6, 3, 1, 1)
        self.pushButton_loanDetails = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_loanDetails.setObjectName("pushButton_loanDetails")
        self.gridLayout_3.addWidget(self.pushButton_loanDetails, 1, 3, 1, 1)
        self.lineEdit_IDBookReturn = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_IDBookReturn.sizePolicy().hasHeightForWidth())
        self.lineEdit_IDBookReturn.setSizePolicy(sizePolicy)
        self.lineEdit_IDBookReturn.setMaximumSize(QtCore.QSize(100, 100))
        self.lineEdit_IDBookReturn.setObjectName("lineEdit_IDBookReturn")
        self.gridLayout_3.addWidget(self.lineEdit_IDBookReturn, 24, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 16, 1, 1, 2)
        self.pushButton_showAvailable = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_showAvailable.sizePolicy().hasHeightForWidth())
        self.pushButton_showAvailable.setSizePolicy(sizePolicy)
        self.pushButton_showAvailable.setObjectName("pushButton_showAvailable")
        self.gridLayout_3.addWidget(self.pushButton_showAvailable, 11, 1, 2, 3)
        self.line_3 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_3.addWidget(self.line_3, 22, 1, 1, 3)
        self.pushButton_deleteMemb = QtWidgets.QPushButton(self.scrollAreaWidgetContents_3)
        self.pushButton_deleteMemb.setObjectName("pushButton_deleteMemb")
        self.gridLayout_3.addWidget(self.pushButton_deleteMemb, 29, 3, 1, 1)
        self.lineEdit_IDMemberReturn = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_IDMemberReturn.sizePolicy().hasHeightForWidth())
        self.lineEdit_IDMemberReturn.setSizePolicy(sizePolicy)
        self.lineEdit_IDMemberReturn.setMaximumSize(QtCore.QSize(100, 100))
        self.lineEdit_IDMemberReturn.setObjectName("lineEdit_IDMemberReturn")
        self.gridLayout_3.addWidget(self.lineEdit_IDMemberReturn, 25, 3, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 18, 1, 1, 3)
        self.radioButton_s2 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_s2.sizePolicy().hasHeightForWidth())
        self.radioButton_s2.setSizePolicy(sizePolicy)
        self.radioButton_s2.setObjectName("radioButton_s2")
        self.gridLayout_3.addWidget(self.radioButton_s2, 3, 2, 1, 1)
        self.radioButton_p2 = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_p2.sizePolicy().hasHeightForWidth())
        self.radioButton_p2.setSizePolicy(sizePolicy)
        self.radioButton_p2.setObjectName("radioButton_p2")
        self.gridLayout_3.addWidget(self.radioButton_p2, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        font.setKerning(False)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 1, 1, 3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_3)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 1, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(210, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 281, 311))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.label_74 = QtWidgets.QLabel(self.groupBox)
        self.label_74.setGeometry(QtCore.QRect(20, 100, 81, 21))
        self.label_74.setObjectName("label_74")
        self.lineEdit_mfn = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_mfn.setGeometry(QtCore.QRect(150, 100, 113, 25))
        self.lineEdit_mfn.setObjectName("lineEdit_mfn")
        self.label_75 = QtWidgets.QLabel(self.groupBox)
        self.label_75.setGeometry(QtCore.QRect(20, 130, 81, 21))
        self.label_75.setObjectName("label_75")
        self.label_76 = QtWidgets.QLabel(self.groupBox)
        self.label_76.setGeometry(QtCore.QRect(20, 220, 81, 21))
        self.label_76.setObjectName("label_76")
        self.dateEdit_paym = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_paym.setGeometry(QtCore.QRect(150, 190, 111, 26))
        self.dateEdit_paym.setDate(QDate.currentDate())
        self.dateEdit_paym.setObjectName("dateEdit_paym")
        self.label_78 = QtWidgets.QLabel(self.groupBox)
        self.label_78.setGeometry(QtCore.QRect(20, 190, 101, 21))
        self.label_78.setObjectName("label_78")
        self.lineEdit_mln = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_mln.setGeometry(QtCore.QRect(150, 130, 113, 25))
        self.lineEdit_mln.setText("")
        self.lineEdit_mln.setObjectName("lineEdit_mln")
        self.pushButton_addNewMember = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_addNewMember.setGeometry(QtCore.QRect(70, 260, 151, 25))
        self.pushButton_addNewMember.setObjectName("pushButton_addNewMember")
        self.lineEdit_mpc = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_mpc.setGeometry(QtCore.QRect(150, 220, 113, 25))
        self.lineEdit_mpc.setText("")
        self.lineEdit_mpc.setObjectName("lineEdit_mpc")
        self.label_79 = QtWidgets.QLabel(self.groupBox)
        self.label_79.setGeometry(QtCore.QRect(90, 30, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_79.setFont(font)
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(self.groupBox)
        self.label_80.setGeometry(QtCore.QRect(20, 160, 91, 21))
        self.label_80.setObjectName("label_80")
        self.dateEdit_memb = QtWidgets.QDateEdit(self.groupBox)
        self.dateEdit_memb.setGeometry(QtCore.QRect(150, 160, 111, 26))
        self.dateEdit_memb.setDate(QDate.currentDate())
        self.dateEdit_memb.setObjectName("dateEdit_memb")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 60, 232, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_p1 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_p1.setObjectName("radioButton_p1")
        self.horizontalLayout_4.addWidget(self.radioButton_p1)
        self.radioButton_s1 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_s1.setObjectName("radioButton_s1")
        self.horizontalLayout_4.addWidget(self.radioButton_s1)
        self.radioButton_r1 = QtWidgets.QRadioButton(self.layoutWidget)
        self.radioButton_r1.setObjectName("radioButton_r1")
        self.horizontalLayout_4.addWidget(self.radioButton_r1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 340, 281, 241))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_73 = QtWidgets.QLabel(self.groupBox_2)
        self.label_73.setGeometry(QtCore.QRect(100, 30, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_73.setFont(font)
        self.label_73.setObjectName("label_73")
        self.label_72 = QtWidgets.QLabel(self.groupBox_2)
        self.label_72.setGeometry(QtCore.QRect(20, 90, 81, 21))
        self.label_72.setObjectName("label_72")
        self.label_71 = QtWidgets.QLabel(self.groupBox_2)
        self.label_71.setGeometry(QtCore.QRect(20, 130, 81, 21))
        self.label_71.setObjectName("label_71")
        self.pushButton_addNewCIty = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_addNewCIty.setGeometry(QtCore.QRect(60, 190, 151, 25))
        self.pushButton_addNewCIty.setObjectName("pushButton_addNewCIty")
        self.lineEdit_city = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_city.setGeometry(QtCore.QRect(150, 90, 113, 25))
        self.lineEdit_city.setText("")
        self.lineEdit_city.setObjectName("lineEdit_city")
        self.lineEdit_pc = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_pc.setGeometry(QtCore.QRect(150, 130, 113, 25))
        self.lineEdit_pc.setText("")
        self.lineEdit_pc.setObjectName("lineEdit_pc")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(310, 20, 281, 311))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_64 = QtWidgets.QLabel(self.groupBox_3)
        self.label_64.setGeometry(QtCore.QRect(100, 30, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.groupBox_3)
        self.label_65.setGeometry(QtCore.QRect(20, 100, 101, 21))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.groupBox_3)
        self.label_66.setGeometry(QtCore.QRect(20, 190, 81, 21))
        self.label_66.setObjectName("label_66")
        self.dateEdit_publish_2 = QtWidgets.QDateEdit(self.groupBox_3)
        self.dateEdit_publish_2.setGeometry(QtCore.QRect(150, 160, 111, 26))
        self.dateEdit_publish_2.setDate(QDate.currentDate())
        self.dateEdit_publish_2.setObjectName("dateEdit_publish_2")
        self.label_67 = QtWidgets.QLabel(self.groupBox_3)
        self.label_67.setGeometry(QtCore.QRect(20, 220, 91, 21))
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(self.groupBox_3)
        self.label_68.setGeometry(QtCore.QRect(20, 130, 81, 21))
        self.label_68.setObjectName("label_68")
        self.lineEdit_pubID = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_pubID.setGeometry(QtCore.QRect(150, 220, 113, 25))
        self.lineEdit_pubID.setText("")
        self.lineEdit_pubID.setObjectName("lineEdit_pubID")
        self.pushButton_addNewBook = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_addNewBook.setGeometry(QtCore.QRect(70, 260, 151, 25))
        self.pushButton_addNewBook.setObjectName("pushButton_addNewBook")
        self.label_69 = QtWidgets.QLabel(self.groupBox_3)
        self.label_69.setGeometry(QtCore.QRect(20, 70, 81, 21))
        self.label_69.setObjectName("label_69")
        self.lineEdit_availNum = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_availNum.setGeometry(QtCore.QRect(150, 100, 113, 25))
        self.lineEdit_availNum.setText("")
        self.lineEdit_availNum.setObjectName("lineEdit_availNum")
        self.lineEdit_title = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_title.setGeometry(QtCore.QRect(150, 130, 113, 25))
        self.lineEdit_title.setText("")
        self.lineEdit_title.setObjectName("lineEdit_title")
        self.lineEdit_type = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_type.setGeometry(QtCore.QRect(150, 190, 113, 25))
        self.lineEdit_type.setText("")
        self.lineEdit_type.setObjectName("lineEdit_type")
        self.lineEdit_isbn = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_isbn.setGeometry(QtCore.QRect(150, 70, 113, 25))
        self.lineEdit_isbn.setObjectName("lineEdit_isbn")
        self.label_70 = QtWidgets.QLabel(self.groupBox_3)
        self.label_70.setGeometry(QtCore.QRect(20, 160, 111, 21))
        self.label_70.setObjectName("label_70")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(610, 20, 281, 191))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        self.lineEdit_IDBook = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_IDBook.setGeometry(QtCore.QRect(150, 100, 113, 25))
        self.lineEdit_IDBook.setText("")
        self.lineEdit_IDBook.setObjectName("lineEdit_IDBook")
        self.lineEdit_IDAuth = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_IDAuth.setGeometry(QtCore.QRect(150, 70, 113, 25))
        self.lineEdit_IDAuth.setText("")
        self.lineEdit_IDAuth.setObjectName("lineEdit_IDAuth")
        self.label_77 = QtWidgets.QLabel(self.groupBox_4)
        self.label_77.setGeometry(QtCore.QRect(20, 70, 81, 21))
        self.label_77.setObjectName("label_77")
        self.label_81 = QtWidgets.QLabel(self.groupBox_4)
        self.label_81.setGeometry(QtCore.QRect(20, 100, 101, 21))
        self.label_81.setObjectName("label_81")
        self.pushButton_addNewAuthBook = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_addNewAuthBook.setGeometry(QtCore.QRect(70, 150, 161, 25))
        self.pushButton_addNewAuthBook.setObjectName("pushButton_addNewAuthBook")
        self.label_82 = QtWidgets.QLabel(self.groupBox_4)
        self.label_82.setGeometry(QtCore.QRect(100, 30, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_82.setFont(font)
        self.label_82.setObjectName("label_82")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_5.setGeometry(QtCore.QRect(610, 360, 281, 221))
        self.groupBox_5.setTitle("")
        self.groupBox_5.setObjectName("groupBox_5")
        self.lineEdit_afn = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_afn.setGeometry(QtCore.QRect(140, 70, 113, 25))
        self.lineEdit_afn.setObjectName("lineEdit_afn")
        self.label_83 = QtWidgets.QLabel(self.groupBox_5)
        self.label_83.setGeometry(QtCore.QRect(30, 100, 81, 21))
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(self.groupBox_5)
        self.label_84.setGeometry(QtCore.QRect(100, 30, 101, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_84.setFont(font)
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.groupBox_5)
        self.label_85.setGeometry(QtCore.QRect(30, 70, 81, 21))
        self.label_85.setObjectName("label_85")
        self.dateEdit_birth = QtWidgets.QDateEdit(self.groupBox_5)
        self.dateEdit_birth.setGeometry(QtCore.QRect(140, 130, 111, 26))
        self.dateEdit_birth.setDate(QDate.currentDate())
        self.dateEdit_birth.setObjectName("dateEdit_birth")
        self.label_86 = QtWidgets.QLabel(self.groupBox_5)
        self.label_86.setGeometry(QtCore.QRect(30, 130, 91, 21))
        self.label_86.setObjectName("label_86")
        self.pushButton_addNewAuthor = QtWidgets.QPushButton(self.groupBox_5)
        self.pushButton_addNewAuthor.setGeometry(QtCore.QRect(70, 180, 151, 25))
        self.pushButton_addNewAuthor.setObjectName("pushButton_addNewAuthor")
        self.lineEdit_aln = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_aln.setGeometry(QtCore.QRect(140, 100, 113, 25))
        self.lineEdit_aln.setText("")
        self.lineEdit_aln.setObjectName("lineEdit_aln")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(610, 210, 281, 151))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_90 = QtWidgets.QLabel(self.groupBox_6)
        self.label_90.setGeometry(QtCore.QRect(90, 30, 101, 17))
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QLabel(self.groupBox_6)
        self.label_91.setGeometry(QtCore.QRect(40, 70, 81, 21))
        self.label_91.setObjectName("label_91")
        self.lineEdit_Pub = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_Pub.setGeometry(QtCore.QRect(130, 70, 113, 25))
        self.lineEdit_Pub.setText("")
        self.lineEdit_Pub.setObjectName("lineEdit_Pub")
        self.pushButton_addNewPub = QtWidgets.QPushButton(self.groupBox_6)
        self.pushButton_addNewPub.setGeometry(QtCore.QRect(70, 110, 151, 25))
        self.pushButton_addNewPub.setObjectName("pushButton_addNewPub")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_7.setGeometry(QtCore.QRect(310, 340, 281, 241))
        self.groupBox_7.setTitle("")
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_92 = QtWidgets.QLabel(self.groupBox_7)
        self.label_92.setGeometry(QtCore.QRect(30, 160, 101, 21))
        self.label_92.setObjectName("label_92")
        self.dateEdit_loan = QtWidgets.QDateEdit(self.groupBox_7)
        self.dateEdit_loan.setGeometry(QtCore.QRect(150, 130, 111, 26))
        self.dateEdit_loan.setDate(QDate.currentDate())
        self.dateEdit_loan.setObjectName("dateEdit_loan")
        self.label_93 = QtWidgets.QLabel(self.groupBox_7)
        self.label_93.setGeometry(QtCore.QRect(110, 30, 71, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.label_93.setFont(font)
        self.label_93.setObjectName("label_93")
        self.pushButton_addNewLoan = QtWidgets.QPushButton(self.groupBox_7)
        self.pushButton_addNewLoan.setGeometry(QtCore.QRect(80, 200, 161, 25))
        self.pushButton_addNewLoan.setObjectName("pushButton_addNewLoan")
        self.label_94 = QtWidgets.QLabel(self.groupBox_7)
        self.label_94.setGeometry(QtCore.QRect(30, 100, 101, 21))
        self.label_94.setObjectName("label_94")
        self.lineEdit_IDBook_2 = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_IDBook_2.setGeometry(QtCore.QRect(150, 100, 113, 25))
        self.lineEdit_IDBook_2.setText("")
        self.lineEdit_IDBook_2.setObjectName("lineEdit_IDBook_2")
        self.dateEdit_deadline = QtWidgets.QDateEdit(self.groupBox_7)
        self.dateEdit_deadline.setGeometry(QtCore.QRect(150, 160, 111, 26))
        self.dateEdit_deadline.setDate(QDate.currentDate().addDays(14))
        self.dateEdit_deadline.setObjectName("dateEdit_deadline")
        self.label_95 = QtWidgets.QLabel(self.groupBox_7)
        self.label_95.setGeometry(QtCore.QRect(30, 70, 91, 21))
        self.label_95.setObjectName("label_95")
        self.label_96 = QtWidgets.QLabel(self.groupBox_7)
        self.label_96.setGeometry(QtCore.QRect(30, 130, 91, 21))
        self.label_96.setObjectName("label_96")
        self.lineEdit_IDMem = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_IDMem.setGeometry(QtCore.QRect(150, 70, 113, 25))
        self.lineEdit_IDMem.setText("")
        self.lineEdit_IDMem.setObjectName("lineEdit_IDMem")
        #self.label_97 = QtWidgets.QLabel(self.tab_2)
        #self.label_97.setGeometry(QtCore.QRect(390, 10, 141, 17))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setBold(True)
        font.setWeight(75)
        #self.label_97.setFont(font)
        #self.label_97.setObjectName("label_97")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Library"))
        self.label_7.setText(_translate("MainWindow", "ID:"))
        self.label_9.setText(_translate("MainWindow", "               Book ID"))
        self.label_6.setText(_translate("MainWindow", "                      Membership Renewal"))
        self.pushButton_showMembers.setText(_translate("MainWindow", "Viev Members"))
        self.label_10.setText(_translate("MainWindow", "           Member ID"))
        self.label_15.setText(_translate("MainWindow", "                                 Deletion"))
        self.label_14.setText(_translate("MainWindow", "Search Author"))
        self.label_4.setText(_translate("MainWindow", "Search Member"))
        self.label_13.setText(_translate("MainWindow", "Book ID"))
        self.label_8.setText(_translate("MainWindow", "                              Book Return"))
        self.radioButton_r2.setText(_translate("MainWindow", "Regular"))
        self.pushButton_return.setText(_translate("MainWindow", "Return Book"))
        self.pushButton_renewal.setText(_translate("MainWindow", "Renewal"))
        self.label_12.setText(_translate("MainWindow", "Member ID"))
        self.label_3.setText(_translate("MainWindow", "Author:"))
        self.pushButton_showAllMembers.setText(_translate("MainWindow", "Show All Members"))
        self.pushButton_deleteBook.setText(_translate("MainWindow", "Delete"))
        self.label.setText(_translate("MainWindow", "ID:"))
        self.pushButton_authorsBooks.setText(_translate("MainWindow", "View Books"))
        self.pushButton_loanDetails.setText(_translate("MainWindow", "Loan Details"))
        self.label_5.setText(_translate("MainWindow", "Search Book"))
        self.pushButton_showAvailable.setText(_translate("MainWindow", "View Available Books"))
        self.pushButton_deleteMemb.setText(_translate("MainWindow", "Delete"))
        self.radioButton_s2.setText(_translate("MainWindow", "Student"))
        self.radioButton_p2.setText(_translate("MainWindow", "Pupil"))
        self.label_11.setText(_translate("MainWindow", "                              Display Data"))
        self.label_2.setText(_translate("MainWindow", "Table view"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "View Data"))
        self.label_74.setText(_translate("MainWindow", "FIrst Name"))
        self.label_75.setText(_translate("MainWindow", "Last Name"))
        self.label_76.setText(_translate("MainWindow", "Postal code"))
        self.dateEdit_paym.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_78.setText(_translate("MainWindow", "Date Payment"))
        self.pushButton_addNewMember.setText(_translate("MainWindow", "Add New Member"))
        self.label_79.setText(_translate("MainWindow", "Add Member"))
        self.label_80.setText(_translate("MainWindow", "Date Memb."))
        self.dateEdit_memb.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.radioButton_p1.setText(_translate("MainWindow", "Pupil"))
        self.radioButton_s1.setText(_translate("MainWindow", "Student"))
        self.radioButton_r1.setText(_translate("MainWindow", "Regular"))
        self.label_73.setText(_translate("MainWindow", "Add City"))
        self.label_72.setText(_translate("MainWindow", "City"))
        self.label_71.setText(_translate("MainWindow", "Postal code"))
        self.pushButton_addNewCIty.setText(_translate("MainWindow", "Add New City"))
        self.label_64.setText(_translate("MainWindow", "Add Book"))
        self.label_65.setText(_translate("MainWindow", "Available num."))
        self.label_66.setText(_translate("MainWindow", "Type"))
        self.dateEdit_publish_2.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_67.setText(_translate("MainWindow", "Publisher ID"))
        self.label_68.setText(_translate("MainWindow", "Title"))
        self.pushButton_addNewBook.setText(_translate("MainWindow", "Add New Book"))
        self.label_69.setText(_translate("MainWindow", "ISBN"))
        self.label_70.setText(_translate("MainWindow", "Date of publish"))
        self.label_77.setText(_translate("MainWindow", "ID Author"))
        self.label_81.setText(_translate("MainWindow", "ID Book"))
        self.pushButton_addNewAuthBook.setText(_translate("MainWindow", "Add New Author/Book"))
        self.label_82.setText(_translate("MainWindow", "Author/Book"))
        self.label_83.setText(_translate("MainWindow", "Last Name"))
        self.label_84.setText(_translate("MainWindow", "Add Author"))
        self.label_85.setText(_translate("MainWindow", "FIrst Name"))
        self.dateEdit_birth.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_86.setText(_translate("MainWindow", "Date of Birth"))
        self.pushButton_addNewAuthor.setText(_translate("MainWindow", "Add New Author"))
        self.label_90.setText(_translate("MainWindow", "Add Publisher"))
        self.label_91.setText(_translate("MainWindow", "Publisher"))
        self.pushButton_addNewPub.setText(_translate("MainWindow", "Add New Publisher"))
        self.label_92.setText(_translate("MainWindow", "Deadline"))
        self.dateEdit_loan.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_93.setText(_translate("MainWindow", "Add Loan"))
        self.pushButton_addNewLoan.setText(_translate("MainWindow", "Add New Loan"))
        self.label_94.setText(_translate("MainWindow", "ID Book"))
        self.dateEdit_deadline.setDisplayFormat(_translate("MainWindow", "yyyy-MM-dd"))
        self.label_95.setText(_translate("MainWindow", "ID Member"))
        self.label_96.setText(_translate("MainWindow", "Date Loan"))
        #self.label_97.setText(_translate("MainWindow", "Database tables"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Populate Database"))
